### ISSUE TITLE
CompositeDisposable вместо списков

### ISSUE THREAD

**Issue by volkodav3107** [mdevilnsk/AndroidTemplates#1]
https://github.com/mdevilnsk/AndroidTemplates/blob/f2f6841c5b67c05116aac66eec5ee51eb680bf79/MVVM/root/src/app_package/mvvm_rx/ViewModel.kt.ftl#L12

это немного странно выглядит( 
можно делать просто CompositeDisposable, потом clear в onCleared, у тебя подписки автоматом отпишутся, но новые будут работать

**Comment by mdevilnsk** [comment]
Thank you for the response. I've fixed it.
