### ISSUE TITLE
Private field

### ISSUE THREAD

**Issue by volkodav3107** [mdevilnsk/AndroidTemplates#2]
https://github.com/mdevilnsk/AndroidTemplates/blob/f2f6841c5b67c05116aac66eec5ee51eb680bf79/MVVM/root/src/app_package/mvvm_rx/ViewModel.kt.ftl#L11

наружу из viewModel может торчать только обычная LiveData, если ты отдаёшь её как Mutable любой может её изменить и ты про это не узнаешь
Если предполагается, что саму LiveData нужно менять, значит должен быть интерфейсный метод, который просто void или boolean, который и осуществляет преобразование, иначе смысл ООП теряется

**Comment by mdevilnsk** [comment]
Thank you for your response. I've fixed it.
